---
title: "Aphid Big 5 Tables"
output:
  officedown::rdocx_document:
    reference_docx: "table_template.docx"
    tables:
      style: "List Table 6 Colorful"
      layout: autofit
      width: 1.0
      caption:
        style: Table Caption
        pre: 'Table '
        sep: ': '
        fp_text: !expr officer::fp_text_lite(bold = TRUE)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library("lme4")
library("car")
library("multcomp")
library("ggplot2")
library("emmeans")
library("piecewiseSEM")
library("MASS")
library("tidyverse")
library("effects")
library("sjPlot")
library("flextable")
library("officedown")
library("officer")

#check wd in R to make sure this is all good
getwd()
file.exists("../Data/big five.csv")

# use this for page based presentations
# geometry: a5paper, margin=20mm, landscape


format_anova = function(model) {
  tab = Anova(model) %>%
  rownames_to_column(var = "Parameter") %>%
  mutate(`Pr(>Chisq)` = ifelse(`Pr(>Chisq)` < 10^-4,
                             paste0("< ", format(10^-4, scientific = TRUE)),
                             format(round(`Pr(>Chisq)`, 2), scientific = FALSE)),
         `LR Chisq` = format(round(`LR Chisq`, 2), scientific = FALSE)
         ) %>%
  rename(
    DF = Df
  ) %>%
  flextable() %>%
  flextable::bold(~ `Pr(>Chisq)` <= 0.05 | `Pr(>Chisq)` == '< 0.0001',4) %>%
  compose(part = "header", j="LR Chisq", value=as_paragraph("\U1D6D8",as_sup("2"))) %>%
  compose(part = "header", j="Pr(>Chisq)", value=as_paragraph(as_i("p"))) %>%
  flextable::width(., width = dim(.)$widths * 6.5 / (flextable::flextable_dim(.)$widths))
  
  return(tab)
}

```

```{r getdata}

# Tables 1-3
bf <- read.csv("../Data/big five.csv") %>%
  mutate(
    Genotype <- as.factor(Genotype)
  ) %>%
  rename(
    Virus = virus
  )
settle.dat <- read.csv("../Data/settle mod.csv", header= TRUE) %>%
  rename(
    "Plant Species" = Plant_sp
  )

# Supp tables
choice.pcr <- read.csv("../Data/test choice pcr.csv", header = TRUE)
repro.pcr <-read.csv("../Data/test reproduction pcr.csv", header=TRUE)
bflc <- read.csv("../Data/big five Logan check.csv", header = TRUE) %>%
  mutate(
    Genotype <- as.factor(Genotype)
  ) %>%
  rename(
    "PEMV (PCR)" = PEMV.PCR
  )
```

```{r tab.cap="Placeholder for Table 1."}

both.bio.mod <- glm.nb(Counts ~ Biotype * Plant * Virus + Run, data = bf)
format_anova(both.bio.mod)

both.bio.cld <- cld(emmeans(both.bio.mod, ~ Biotype|Plant|Virus, adjust="none", type="response"), sort=FALSE, Letters=c("abc"))
both.bio.cld$.group=gsub(" ", "", both.bio.cld$.group)
both.bio.cld$emmean <- both.bio.cld$response

```


```{r tab.cap="Placeholder for Table 2."}

new.count.mod <- glm(Counts ~ Biotype*`Plant Species`*Virus, data=settle.dat)
format_anova(new.count.mod)

count.lsm <- cld(emmeans(new.count.mod, ~ Biotype|`Plant Species`|Virus), sort=FALSE, adjust="none", type="response")
count.lsm$.group=gsub(" ", "", count.lsm$.group)

```


```{r tab.cap="Placeholder for Table 3."}

pxp <- as.data.frame(count.lsm)

#compare to order from both.bio.cld (performance assay)
bbc.dat <- as.data.frame(both.bio.cld)

pxp$Performance <- bbc.dat$response
pxp$preference <- count.lsm$emmean

# glm for preference by performance

glm(preference ~ Performance*Virus, data=pxp) %>%
  format_anova()

```


```{r tab.cap="Placeholder for Table S1."}

glm(PEMV ~ Virus, family=binomial, data=choice.pcr) %>%
  format_anova()

```


```{r tab.cap="Placeholder for Table S2."}

glm(PEMV ~ Virus, family=binomial, data=repro.pcr) %>%
  format_anova()

```


```{r tab.cap="Placeholder for Table S3."}
bflc[bflc==""] <- NA
bflc.2 <- subset(bflc, virus != "BLRV")

glm(Counts ~ `PEMV (PCR)`*Plant, data=bflc.2) %>%
  format_anova()

```